name: "\U0001F4D5 Documentation Issue"
description: Report an issue in the README.md
title: "(short issue description)"
labels: [documentation, needs-triage]
assignees: []
body:
  - type: markdown
    id: deprecation
    attributes:
      value: |
        Support for this project will end on 2026-05-31. Please consider migrating to https://www.github.com/aws/aws-advanced-odbc-wrapper
  - type: textarea
    id: description
    attributes:
      label: Describe the issue
      description: A clear and concise description of the issue.
    validations:
      required: true
  - type: textarea
    id: links
    attributes:
      label: Links
      description: |
        Include links to affected documentation page(s).
    validations:
      required: true
