#! /bin/sh

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2.0
# (GPLv2), as published by the Free Software Foundation, with the
# following additional permissions:
#
# This program is distributed with certain software that is licensed
# under separate terms, as designated in a particular file or component
# or in the license documentation. Without limiting your rights under
# the GPLv2, the authors of this program hereby grant you an additional
# permission to link the program and your derivative works with the
# separately licensed software that they have included with the program.
#
# Without limiting the foregoing grant of rights under the GPLv2 and
# additional permission as to separately licensed software, this
# program is also subject to the Universal FOSS Exception, version 1.0,
# a copy of which can be found along with its FAQ at
# http://oss.oracle.com/licenses/universal-foss-exception.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License, version 2.0, for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see 
# http://www.gnu.org/licenses/gpl-2.0.html.

# Must be either Debug or Release
CONFIGURATION=$1
echo ${CONFIGURATION}
if [ "${CONFIGURATION}" != "Debug" ] && [ "${CONFIGURATION}" != "Release" ]; then
  echo "Build configuration must be Debug or Release"
  exit 1
fi

export ROOT_REPO_PATH=$(cd "$(dirname "$0")/.."; pwd -P)

# Build the AWS SDK
echo "Building the AWS SDK"
cd ${ROOT_REPO_PATH}/libs/aws-rds-odbc
scripts/build_aws_sdk_macos ${CONFIGURATION}
if [ $? -ne 0 ]; then
  echo "AWS SDK build failed"
  exit 1
fi

# Prep the aws-rds-odbc builds
echo "Prepping the ansi aws-rds-odbc build"
cmake -S . -B build_ansi
if [ $? -ne 0 ]; then
  echo "ansi aws-rds-odbc build prep failed"
  exit 1
fi

echo "Prepping the unicode aws-rds-odbc build"
cmake -S . -B build_unicode -DUNICODE_BUILD=ON
if [ $? -ne 0 ]; then
  echo "unicode aws-rds-odbc build prep failed"
  exit 1
fi

# Build aws-rds-odbc
echo "Building ansi version of aws-rds-odbc"
cmake --build build_ansi --config ${CONFIGURATION}
if [ $? -ne 0 ]; then
  echo "ansi aws-rds-odbc build failed"
  exit 1
fi

echo "Building unicode version of aws-rds-odbc"
cmake --build build_unicode --config ${CONFIGURATION}
if [ $? -ne 0 ]; then
  echo "unicode aws-rds-odbc build failed"
  exit 1
fi

# Prep and build aws-pgsql-odbc
echo "Prepping the aws-pgsql-odbc build"
cd ${ROOT_REPO_PATH}
./bootstrap
if [ $? -ne 0 ]; then
  echo "bootstrap failed"
  exit 1
fi

./configure --with-unixodbc=/opt/homebrew/bin/odbc_config --disable-dependency-tracking
if [ $? -ne 0 ]; then
  echo "configure failed"
  exit 1
fi

echo "Building aws-pgsql-odbc"
make
