name: Dockerized Linux Regression Tests
run-name: aws-pgsql-odbc Dockerized Linux Regression Tests - ${{ github.event.head_commit.message }}

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '**/*.md'
      - '**/*.jpg'
      - '**/*.png'
      - '**/README.*'
      - '**/LICENSE.*'
      - 'docs/**'
      - 'ISSUE_TEMPLATE/**'
      - '**/remove-old-artifacts.yml'
      - '**/release.yml'

concurrency:
  group: linux-regression-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux-regression-tests:
    name: Linux Regression Tests
    runs-on: ubuntu-latest
    env:
      CMAKE_GENERATOR: Unix Makefiles

    steps:
      - name: Checkout aws-pgsql-odbc
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 1

      - name: Initialize submodules
        run: |
          git submodule update --init --recursive

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17
      
      - name: Run Community Tests
        working-directory: ${{ github.workspace }}/testframework
        run: |
          ./gradlew --no-parallel --no-daemon test-community --info
        env:
          TEST_USERNAME: postgres
          TEST_PASSWORD: test
          DRIVER_PATH: ${{ github.workspace }}
