name: Build And Regression Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

env:
  BUILD_TYPE: Release
  CMAKE_GENERATOR: Visual Studio 17 2022

jobs:
  build-and-test-driver:
    name: Build and run regression tests
    runs-on: windows-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.3.2

      - name: Cache AWS SDK libraries
        id: cache-dynamic-aws-sdk
        uses: actions/cache@v4
        with:
          path: |
            aws_sdk
          key: ${{ runner.os }}-aws-sdk-dynamic-lib

      - name: Build the AWS SDK C++
        working-directory: ./scripts
        if: steps.cache-dynamic-aws-sdk.outputs.cache-hit != 'true'
        run: |
          .\build_aws_sdk_win.ps1 x64 ${{ env.BUILD_TYPE}} OFF "${{env.CMAKE_GENERATOR}}"

      - name: Build the driver
        working-directory: ./winbuild
        run: .\BuildAll.ps1 -Platform x64

      - name: Setup nmake
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build the installer
        working-directory: ./installer
        run: |
          mkdir x64
          .\buildInstallers.ps1 x64

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: AWSPgODBC Installer
          path: ./installer/x64/*.msi
          retention-days: 5
          if-no-files-found: error
